### PR TITLE
Add script to make PDF book from HTML

### LINKED ISSUE #4: Script to convert book to pdf
Currently the book is not available as a pdf. Some people would like to read it in this form.

To this end, we need a python script which does the following.

* Convert the entire book into a single pdf.
* All sections of each chapter should be joined without a page break.
* There should be a page break between chapters.
* There should be a a cover page. It can consist of a dummy image for now.
* There should be a table of contents. The `toc.py` script creates the table and contents for the .ipynb version of the book. This might be adapted to our purposes.
* All pages should be numbered. I like to start numbering from the cover page, so there is no discrepancy between the pdf page numbers and the book page numbers.
* All internal links in the book should be transformed into pdf links. (Optional)

Based on my research [WeasyPrint](https://doc.courtbouillon.org/weasyprint/stable/) seems to be a library that can do this. But I am open to alternate suggestions that work on Debian linux.

If you are interested in this issue, please comment below and I will assign you to it.

### PR DESCRIPTION
**Pull request by schance995**
Playwright was chosen because weasyprint cannot render Javascript. On my Arch Linux laptop it takes ~2 seconds to load the page with hardware acceleration and ~130 seconds without hardware acceleration.

### CODE REVIEW

**Comment by abdullahkhalids** [comment]
Thank you for the pull request. I tested it on my computer. A few issues.

* I think `lxml` library is also required, but not present in requirements.txt. I had to install it for the code to run.
* In my build, raw latex code is displayed instead of maths.

image

I see this is because you are using node for mathjax. The install steps for this are missing. But do we need to do this? Node is a pretty heavy install requirement. Can we just use the existing online script to render the page?

* How can we move the page numbers to either the center or to the center right like is common in books?

* Can you also add some code, showing how to add and remove css files? This can be commented out for now. For the actual build I would like to change fonts and colors etc to be print friendly.

**Comment by abdullahkhalids** [comment]
About point 2. I played around with it. I commented out the mathjax line

```
script["src"] = script["src"].replace("https://cdn.jsdelivr.net/npm/mathjax@3.0.0/", "node_modules/mathjax/")
```
and down below I changed

```
    page.goto(html, wait_until='load')
    time.sleep(10)
```
That seems to give enough time for the mathjax to load. I don't know if 'load' is the correct argument here. Maybe not the nicest way of doing this, but it does work. Maybe there is a better way.

**Comment by schance995** [comment]
> About point 2. I played around with it. I commented out the mathjax line
> 
> ```
> script["src"] = script["src"].replace("https://cdn.jsdelivr.net/npm/mathjax@3.0.0/", "node_modules/mathjax/")
> ```
> 
> and down below I changed
> 
> ```
>     page.goto(html, wait_until='load')
>     time.sleep(10)
> ```
> 
> That seems to give enough time for the mathjax to load. I don't know if 'load' is the correct argument here. Maybe not the nicest way of doing this, but it does work. Maybe there is a better way.

I tested this and it works for me. I think it's the best way without writing more Javascript to hook into the end of Mathjax loading.

**Comment by schance995** [comment]
>     * I think `lxml` library is also required, but not present in requirements.txt. I had to install it for the code to run.

I will add this to requirements.txt.

>     * How can we move the page numbers to either the center or to the center right like is common in books?

The footer_template argument needs to be styled. It's not exactly straightforward, see https://github.com/microsoft/playwright/issues/14441#issuecomment-1259718342

>     * Can you also add some code, showing how to add and remove css files? This can be commented out for now. For the actual build I would like to change fonts and colors etc to be print friendly.

Currently the book.html file uses the same CSS files as the web version. I can change the code to use a list of CSS files instead of (or along with) those used in the web version.

**Comment by abdullahkhalids** [comment]
For the footer, I played around with it a bit. This works well enough, to look decent. Kindly add this.

```
             footer_template='<span class="pageNumber" style="position: absolute; left: 62%; font-size: 10px;"></span>',
             margin={
                 "top": "1cm",
                 "right": "2cm",
                 "bottom": "1cm",
                 "left": "2cm",
             })
```

**Pull request merged**
