### PR TITLE
Implementation of color codes

### LINKED ISSUE #3: Implementation of color codes
A future chapter of the book will discuss color codes.

Implement the syndrome measurements for the [color code](https://errorcorrectionzoo.org/c/color) in [stac](https://github.com/abdullahkhalids/stac). In particular, we are looking for an implementation of the 2D 4.8.8 color code family (see [here](https://arxiv.org/pdf/1108.5738.pdf))

Please see how [standard syndrome measurements](https://github.com/abdullahkhalids/stac/blob/b48947207dcca3e472729dfbf74e787f9538eed9/stac/code.py#LL777C15-L777C15) are implemented.

~~This is a good opportunity to use coordinate based addressing of qubits: see last section of this [guide](https://github.com/abdullahkhalids/stac/wiki/guide). I also wrote a detailed explanation for how to do this for surface codes [here](https://github.com/abdullahkhalids/qecft/pull/5#issuecomment-1569370695).~~

To complete this issue, please create a .py file in the drafts folder that contains a function `_color_codes_syndrome_measurements`.

### PR DESCRIPTION
**Pull request by victor-onofre**
The first dirty version of the function only works for a code of distance 3. I will work on the following list of to-do's:

- [x] Correct the heights of each column and how to add diagonal edges for N=5,9,... in the function `vertices_physical_qubits`
- [x] Right now, I only have the measurement for faces of 4 edges, I need to add the one for 8 edges.
- [x] Generalizations for a general distance `d`
- [x] Clean the code

### CODE REVIEW

**Comment by abdullahkhalids** [comment]
Great work. You have a solid base on which to improve upon. The rest is mostly just adding the correct if conditions in the right places.

**Comment by abdullahkhalids** [comment]
This `new_odd` business is not elegant. Please note that if $N = 5,9,...$ then $N-1$ is divisible by 4. You should use this condition instead.

**Comment by victor-onofre** [comment]
The solution is so simple with the condition `N-1` being divisible by 4. I don't know how I didn't see it

**Comment by victor-onofre** [comment]
@abdullahkhalids I think the way I have constructed the cat states for the 8 qubits stabilizers is correct. It follows the structure of your example but with the appropriate indices of the ancilla qubits

**Comment by abdullahkhalids** [comment]
Hey! I took a look. Registers are correctly made. There seems to be one small error. First, please note that you can look at the circuits easily by doing

```
_color_codes_syndrome_measurements(5).draw('text', 'colorcirc.text')
```
Then open `colorcirc.text` in a text editor with horizontal scrolling.

In lines 164 and 175, it should be `face` instead of `i`.

```
number = qubit_number.index(faces[face][j])
```
Please fix this. And we should be done.

But I will make one suggestion. In python, its not elegant to do `for face in range(len(faces)):`. The better way is `for face, f in enumerate(faces)`. Then `face` is the list item, and `f` is the index of that list item. This means, instead of writing

```
    for face in range(len(faces)):
        if len(faces[face]) == 4:
            circ.append('H', (0, 1, 1, face, 0))
            for j in range(len(faces[i])):
                number = qubit_number.index(faces[face][j])
```
you write
```
    for face, f in enumerate(faces):
        if len(face) == 4:
            circ.append('H', (0, 1, 1, f, 0))
            for j in range(4): # you already know face is length 4
                number = qubit_number.index(face[j])
                ...
```
See how much easier it is to read.

**Comment by abdullahkhalids** [comment]
Thank you. I have accepted the pull request.

**Pull request merged**
