### PR TITLE
Isso integration

### LINKED ISSUE #2: Forum for solutions
The book has many tasks for the user to do. Instead of providing solutions, I would like to create a forum associated with the book for  discussing solutions to these tasks.

To this end, we need to

* Select a simple forum system. Even a commenting system would work well.
* For each Task, create a page for discussing its solutions.
* Link to this page from the Task.

For the system, some nice features would be
* Written in python or similar language, so its easy for me to make changes.
* Doesn't require logins because I don't want to store user data. Just enter your name and email and submit a comment. This makes GDPR compliance easy because we are storing minimal data, but does cause issues with users wanting to delete or edit their answers.
* Threaded replies
* Voting, and sorting by voting.

 Currently leaning towards [isso](https://github.com/posativ/isso/). But open to suggestions to alternates.

To complete this issue, please

1. Start a discussion here on the details of the system. Please only start work once you are assigned to this issue.
2. Create an install script for all necessary software and their configuration on a standard ubuntu LTS server.
3. Some script to create a page for each task and link to that page from within the notebooks.

A small team working on this team is welcome.

### PR DESCRIPTION
**Pull request by AnsahMohammad**
Implemented the local integration with isso.
Tasks
- [x] A script to create tasks 
- [x] Integrated with isso
- [x] script to install dependencies and configuration in Ubuntu LTS server
- [x] Linking to the notebook

This draft PR closes #2 once merged

### CODE REVIEW

**Comment by AnsahMohammad** [comment]
@abdullahkhalids I've added a local implementation of the issue. Please review it once.

for now, I have linked the `chapters/cec/` with the isso,
first make sure to run the server by entering `./forum.sh`
Then you can normally open the notebook and click on the hyperlink which directs to the Discussion generating page.

This is just initial implementation, open to suggestions. Thank you!

**Comment by abdullahkhalids** [comment]
I played around with this a bit. This looks good. I really like the idea for the webpage to create the task pages.

Two related comments.

- Please remove the changes to the notebooks from the PR.
- When we click on "Create Page", please output a markdown string that I can paste into the notebook. Eg. if we just created "section2.1task1.html", then just output the string

```
[Discussion](https://abdullahkhalid.com/qecft/solutions/section2.1task1.html)
```
Hope this makes sense.

Edit: Also please change the virtual environment invocation from `venv` to the more modern `virtualenv`.

**Comment by AnsahMohammad** [comment]
Are you suggesting to display the markdown string for the link instead of redirecting to the task-comments page ?

Or do you want to add the markdown string along with the Task-comments page ?

**Comment by abdullahkhalids** [comment]
> Are you suggesting to display the markdown string for the link instead of redirecting to the task-comments page ?

Yes. No redirects. Just on the same "create page" show the markdown for the link, and perhaps just the link itself in case I want to check out the task page.

**Comment by AnsahMohammad** [comment]
Okay!!, I thought that page was meant for users.
Now it makes more sense 👍.
I'll make necessary changes asap

**Comment by AnsahMohammad** [comment]
@abdullahkhalids Check this out now!

**Comment by abdullahkhalids** [comment]
This looks very good. This is basically ready. Just some minor changes.

* The `isso.cfg` is in the root directory. But in `forum.sh`, it is expected in the forum subfolder. Please move the file into the subfolder.
* Kindly move the forum building instructions in the readme below the "## Building the table of contents for the jupyter notebooks"
* Rename `forum/templates` to `forum/createpage`. Leave the `index.html` there.
* Instead of creating the task pages in the now renamed `forum/templates` create them in `forum/solutions`.
* Along the same lines `link_output` in `forumcreator.py` should be `f"/solutions/{page_filename}"`. The `app.route` below that will change similarly.

Finally, to include you in the contributors list, can you
* State your "Full name <email>" or other way of contacting you.
* Agree to release all code you have written as GPLV3? Of course, you don't have to, if you don't want to.

**Comment by AnsahMohammad** [comment]
Full Name: Mohammad Ansah
Contact: mohdansah10@gmail.com

I agree to release all the code I have written for this repository under the GPLV3 license.

**Pull request merged**
